image: node:20
pipelines:
  default:
    - step:
        name: DEBUG - Verificando Chave
        script:
          - echo 'Iniciando debug da chave SSH...'
          - echo "${SSH_KEY}" > chave_privada.tmp
          - chmod 600 chave_privada.tmp
          - echo 'Chave publica gerada pela pipeline:'
          - ssh-keygen -y -f chave_privada.tmp
          - echo 'Debug finalizado.'