image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Code Linting
            caches:
              - node
            script:
              - npm install
              - npx eslint .
    - step:
        name: Mirror to GitHub
        services:
          - docker
        script:
          - mkdir -p ~/.ssh
          - echo "${SSH_KEY}" > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan github.com >> ~/.ssh/known_hosts
          - git remote add github-mirror git@github.com:SamaraSilvia81/agenda-de-compromissos-socket.git
          - git push --all github-mirror
