image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn install
              - yarn test
        - step:
            name: Code Linting
            caches:
              - node
            script:
              - yarn install
              - yarn eslint .
    - step:
        name: Mirror to GitHub
        script:
          - mkdir -p ~/.ssh
          - echo "${SSH_KEY}" | base64 --decode > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan github.com >> ~/.ssh/known_hosts
          - git remote add github-mirror git@github.com:SamaraSilvia81/agenda-de-compromissos-socket.git
          - git push --all github-mirror
    - step:
        name: Build and Push to Docker Hub
        services:
          - docker
        script:
          - echo $DOCKER_HUB_APP_PASSWORD | docker login --username $DOCKER_HUB_USER --password-stdin
          - docker build -t samarasilvia81/agenda-de-compromissos-socket:latest .
          - docker push samarasilvia81/agenda-de-compromissos-socket:latest