image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Code Linting
            caches:
              - node
            script:
              - npm install
              - npx eslint .
    - step:
        name: Mirror to GitHub
        script:
          - echo $SSH_KEY | base64 -d | ssh-agent -s
          - ssh-add
          - git remote add github-mirror git@github.com:SamaraSilvia81/agenda-de-compromissos-socket.git
          - git push --all github-mirror
